### ISSUE TITLE
config.yml media_folder and public_folder paths

### ISSUE THREAD

**Issue by anthonysapp** [netlify-templates/kaldi-hugo-cms-template#1]
Shouldn't the config paths be as follows, for a default?

```
media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "/img"
```

The ones currently in the repo don't work for adding _image_ front matter and inline images in a new post.

**Comment by erquhart** [comment]
@anthonysapp they should work in the generated site, but viewing in the CMS itself has issues: https://github.com/netlify/netlify-cms/issues/229

Is that what you're referring to?

**Comment by anthonysapp** [comment]
I believe it was actually in the generated site, but I'll have to double check. Closing this for now.
