### ISSUE TITLE
Error signing into `/admin` (The redirect_uri MUST match the registered callback URL for this application.)

### ISSUE THREAD

**Issue by AeonFr** [netlify-templates/kaldi-hugo-cms-template#11]
I followed the steps to install this repository under a netlify site.
This is what my Github OAuth Application's settings look like.

![picture01](https://cloud.githubusercontent.com/assets/11742754/26756946/f6575426-4883-11e7-912f-39f466d4d9f0.png)

(The **Authorization callback URL** setting was filled automatically by GitHub, unfortunately appending `/admin` to that value doesn't causes the error to go away)

So basically I went to netlify and added the authentification provider.
Everything good so far.
Now, when hitting the /admin page of my site I see this beautiful big button...

![picture02](https://cloud.githubusercontent.com/assets/11742754/26756960/7ff7f5e6-4884-11e7-92ae-8d36579c1e44.png)

And it opens a modal... But here an error appears.
This is the screen of the modal

![image](https://cloud.githubusercontent.com/assets/11742754/26756964/b23e2b24-4884-11e7-8e02-9191f86dbbf6.png)

Not only I did not sign in, I get the error that can be seen clearly in the URL of the opened pop-up:

https://jockey-stabilization-30351.netlify.com/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=59331cb8a700c409d17d003c

```
error:redirect_uri_mismatch
error_description:The redirect_uri MUST match the registered callback URL for this application.
error_uri:https://developer.github.com/v3/oauth/#redirect-uri-mismatch
state:59331cb8a700c409d17d003c
```

I'm pretty sure I'm not fully understanding what to put in the OAuth App configuration, but maybe I simply failed while doing something else. Any help would be appreciated.

**Comment by erquhart** [comment]
The CMS quick start guide provides instructions for setting up OAuth: https://www.netlifycms.org/docs/quick-start/

Your callback url should be https://api.netlify.com/auth/done.

Closing, but feel free to comment if there are further issues, or join us on [Gitter](https://gitter.im/netlify/NetlifyCMS).
