### ISSUE TITLE
hugo binaries version

### ISSUE THREAD

**Issue by smakinson** [netlify-templates/kaldi-hugo-cms-template#16]
Quick question. Which hugo binaries are included? These?

Linux-64bit.tar.gz
macOS-64bit.tar.gz
Windows-64bit.zip

**Comment by erquhart** [comment]
Judging by the date of the [commit](https://github.com/netlify-templates/kaldi-hugo-cms-template/commit/9dde2ed6d67ef7bd094612c21afe565d38ef91fd), I'd say [0.18.1](https://github.com/gohugoio/hugo/releases/tag/v0.18.1). We definitely need an update - [hugo-bin](https://github.com/fenneclab/hugo-bin) looks like a great way to manage this moving forward.
