### ISSUE TITLE
Admin can not login with github account in firefox browser

### ISSUE THREAD

**Issue by MuhRizal** [netlify-templates/kaldi-hugo-cms-template#22]
I have an issue when login with github account in mozilla firefox.
Note: It is working fine in chrome browser.
This is the message in firefox console:
```
Problem fetching repo data from GitHub cms.js:4219:24590
	value/< https://cashier-fox-11043.netlify.com/cms.js:4219:24590
```

**Comment by tech4him1** [comment]
@MuhRizal Please visit the CMS directly: www.netlifycms.org.
