### ISSUE TITLE
Archive or Update

### ISSUE THREAD

**Issue by tech4him1** [netlify-templates/kaldi-hugo-cms-template#23]
This template doesn't seem to be updated anymore, but the (mostly identical) `one-click-hugo-cms` template is. Should this one be updated or archived/deleted?

**Comment by erquhart** [comment]
I'm okay with archiving, maintaining both isn't realistic. We'd need to get some of the updates from this version ported over before doing so, such as the CSS updates from @covingtondoan that I'm about to merge.

cc/ @calavera @biilmann

**Comment by easherma** [comment]
+1 on this, I'm confused as to which one would be preferred to use or what the differences are?

**Comment by erquhart** [comment]
The big difference is the other one is made to work with Git Gateway and Netlify Identity, but it still supports everything this one does. If in doubt go with the other one.

**Comment by erquhart** [comment]
Archiving.
