### ISSUE TITLE
Collapsible nav

### ISSUE THREAD

**Issue by modille** [netlify-templates/kaldi-hugo-cms-template#6]
Any plans or interest in making the nav collapse on small screens, rather than scroll horizontally?

I was thinking along the lines of:

https://v4-alpha.getbootstrap.com/components/navbar/#responsive-behaviors

http://materializecss.com/navbar.html#mobile-collapse

**Comment by erquhart** [comment]
Collapsible nav would be a good improvement, I think we'd be open to a PR for that.

**Comment by modille** [comment]
I didn't notice this before, but it looks like Tachyons doesn't have a collapsible nav out of the box (which would have made it much easier).

http://tachyons.io/components/#nav

**Comment by erquhart** [comment]
Yeah, Tachyons is css only.

**Comment by atelierbram** [comment]
Just did [a PR](https://github.com/netlify-templates/kaldi-hugo-cms-template/pull/19) for this issue
